// Copies the InstantWallet + Factory ABIs from forge's out/ into lib/abi.ts (run after `forge build`).
import { readFileSync, writeFileSync } from "node:fs";
const out = new URL("../../packages/foundry/out/", import.meta.url);
const abi = name => JSON.parse(readFileSync(new URL(`${name}.sol/${name}.json`, out))).abi;
const body = ["InstantWallet", "Factory"]
  .map(n => `export const ${n[0].toLowerCase() + n.slice(1)}Abi = ${JSON.stringify(abi(n), null, 2)} as const;\n`)
  .join("\n");
writeFileSync(new URL("../lib/abi.ts", import.meta.url), `// Generated by tools/abi.mjs from packages/foundry/out. Do not edit.\n\n${body}`);
console.log("lib/abi.ts written");
