/**
 * Minimal type used by the autogenerated `contracts/deployedContracts.ts`.
 * (The Scaffold-ETH hook machinery was removed; only the declaration shape is kept.)
 */
export type GenericContract = {
  address: string;
  abi: readonly unknown[];
  inheritedFunctions?: Record<string, string>;
  deploymentFile?: string;
  deploymentBlockNumber?: number;
};

export type GenericContractsDeclaration = {
  [chainId: number]: {
    [contractName: string]: GenericContract;
  };
};
